version: '3.9'

services:
  mongo:
    image: mongo:6
    container_name: birthday-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: ./user-management
    container_name: user-management
    restart: always
    command: node dist/main.js
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/birthday-db
    depends_on:
      - mongo

  worker:
    build: ./birthday-worker
    container_name: birthday-worker
    restart: always
    command: node dist/main.js
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/birthday-db
    depends_on:
      - mongo

volumes:
  mongo_data: